###
POST http://localhost:8080/daily-bugle-angular/api/users/register
Content-Type: application/json

{
  "email": "loius@test.com",
  "password": "4567",
  "displayName": "Lois Lane",
  "role": "JOURNALIST"
}


###
POST http://localhost:8080/daily-bugle/api/users/register
Content-Type: application/json

{
  "email": "reader@test.com",
  "password": "1234",
  "displayName": "Mary Jane",
  "role": "READER"
}

###
POST http://localhost:8080/daily-bugle/api/users/login
Content-Type: application/json

{
  "email": "loius@test.com",
  "password": "4567"
}

###
POST http://localhost:8080/daily-bugle/api/users/login
Content-Type: application/json

{
  "email": "reader@test.com",
  "password": "1234"
}

###
POST http://localhost:8080/daily-bugle/api/articles
Content-Type: application/json
X-User-Id: 1

{
  "title": "Daily Bugle Breaking News",
  "synopsis": "Something big happened",
  "content": "Full article content here..."
}

###
POST http://localhost:8080/daily-bugle/api/comments
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "content": "Great article!"
}

###
POST http://localhost:8080/daily-bugle/api/ratings
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "value": 5
}

###
POST http://localhost:8080/daily-bugle/api/ratings
Content-Type: application/json
X-User-Id: 2

{
  "articleId": 1,
  "value": 4
}

###
GET http://localhost:8080/daily-bugle/api/users/2

###
GET http://localhost:8080/daily-bugle/api/users/1

###
POST  http://localhost:8080/daily-bugle/api/articles
Content-Type: application/json
X-User-Id: 1

{
  "title": "Daily News",
  "synopsis": "Something happened",
  "content": "Full article content here...",
  "publishAt": "2026-02-05T10:00:00Z"
}


###
GET http://localhost:8080/daily-bugle/api/articles/1

###
POST  http://localhost:8080/daily-bugle/api/articles
Content-Type: application/json
X-User-Id: 1

{
  "title": "What a discovery",
  "synopsis": "Something happened with science",
  "content": "Full article content here...",
  "publishAt": "2026-02-10T10:00:00Z",
  "category": "SCIENCE"
}

###
GET http://localhost:8080/daily-bugle/api/articles/category

###
POST http://localhost:8080/daily-bugle/api/ratings
X-User-Id: 2
Content-Type: application/json

{
  "articleId": 2,
  "value": 4
}

###
POST  http://localhost:8080/daily-bugle/api/articles
Content-Type: application/json
X-User-Id: 1

{
  "title": "Advanced Java",
  "synopsis": "Streams and more",
  "content": "Deep dive...",
  "category": "TECHNOLOGY",
  "publishAt": null,
  "keywords": ["java"]
}

###
GET http://localhost:8080/daily-bugle/api/articles/by-keyword/java

###
PUT  http://localhost:8080/daily-bugle/api/articles/1
Content-Type: application/json
X-User-Id: 1

{
  "title": "Spring Boot Guide UPDATED",
  "synopsis": "Updated synopsis",
  "content": "Updated content",
  "category": "TECHNOLOGY",
  "publishAt": null,
  "keywords": ["docker", "kubernetes"]
}

###
PUT http://localhost:8080/daily-bugle/api/admin/users/2/deactivate
X-User-Id: 2

